#!/bin/bash

# Script to refresh AWS SSO credentials for Next.js development
# Run this before starting the dev server: ./refresh-aws-creds.sh

set -e

echo "Refreshing AWS SSO credentials..."

# Get credentials from AWS SSO
CREDENTIALS=$(aws configure export-credentials --profile default --format env-no-export)

if [ $? -ne 0 ]; then
    echo "Error: Failed to get AWS credentials."
    echo "Make sure you're logged in with: aws sso login --profile default"
    exit 1
fi

# Parse credentials
export $(echo "$CREDENTIALS" | xargs)

# Update .env.local with fresh credentials
cat > .env.local << EOF
# AWS SSO Credentials (auto-generated by refresh-aws-creds.sh)
# Refresh these when they expire by running: ./refresh-aws-creds.sh
AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN
AWS_REGION=us-west-2

# Credential expiration: $AWS_CREDENTIAL_EXPIRATION

# Optional: Add other AI provider keys if needed
# GOOGLE_GENERATIVE_AI_API_KEY="your-google-api-key-here"
# OPENAI_API_KEY="your-openai-api-key-here"
# OPENROUTER_API_KEY="your-openrouter-api-key-here"
EOF

echo "✓ Credentials refreshed successfully!"
echo "Credentials will expire at: $AWS_CREDENTIAL_EXPIRATION"
echo ""
echo "Now you can start the development server with: npm run dev"
